const paths = {
    homepage: 'homepage',
    menpage: 'menpage',
    womenpage: 'womenpage',
    kidspage: 'kidspage',
    collectionspage: 'collectionspage',
    collectionstopspage:'collectionstopspage',
    collectionsjeanspage: 'collectionsjeanspage',
    collectionsjacketpage: 'collectionsjacketpage',
    collectionsshoespage: 'collectionsshoespage',
    mentopspage:'mentopspage',
    menjeanspage: 'menjeanspage',
    menjacketpage: 'menjacketpage',
    menshoespage: 'menshoespage',
    womentopspage:'womentopspage',
    womenjeanspage: 'womenjeanspage',
    womenjacketpage: 'womenjacketpage',
    womenshoespage: 'womenshoespage',
    kidstopspage:'kidstopspage',
    kidsjeanspage: 'kidsjeanspage',
    kidsjacketpage: 'kidsjacketpage',
    kidsshoespage: 'kidsshoespage',
    productpage: 'productpage',
    cartpage: 'cartpage',
  }